<a href="https://colab.research.google.com/github/x4ddy/CC_Coursework/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

**Q.1** Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:

a) Addition of 2 in all the element

b) Multiply 3 with all the elements

c) Divide every element by 2

In [ ]:
arr1 = np.array([2,4,6,8,9])
arr2 = arr1+2
print(arr2)
arr3 = arr1*3
print(arr3)
arr4 = arr1/2
print(arr4)


[ 4  6  8 10 11]
[ 6 12 18 24 27]
[1.  2.  3.  4.  4.5]


**Q.2** Questions on Basic NumPy Array:

**a)** Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [ ]:
arr = np.array([1, 2, 3, 6, 4, 5])
print(arr[::-1])

[5 4 6 3 2 1]


**Q.2**

**b)** Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
elems, counts = np.unique(x, return_counts=True)
print(elems)
print(counts)
print(f'Element with the most occurences : {elems[np.argmax(counts)]}')
elemsY, countsY = np.unique(y, return_counts=True)
print(elemsY)
print(countsY)
print(f'Element with the most occurences : {elems[np.argmax(counts)]}')

[1 2 3 4 5]
[5 2 1 1 1]
Element with the most occurences : 1
[1 2 3 4]
[3 2 3 2]
Element with the most occurences : 1


**Q.3** For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:

a) Access 1st row, 2nd column

b) Access 3rd row, 1st column

In [ ]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[0,1])
print(arr[2,0])

20
70


**Q.4** Write program to create an 1-D NumPy array named <<\Your Name>> with evenly spaced 25 numbers from 10 to 100 using linspace().

Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array.

 Find the transpose of this array using reshape() attribute.

Can we do the same with T attribute?

In [ ]:
MayankSangwan= np.linspace(10,100,25)
print(f'The array formed :{MayankSangwan}')
print(f'Dimensions :{MayankSangwan.ndim}')
print(f'Shape: {MayankSangwan.shape}')
print(f'Elements: {MayankSangwan.size}')
print(f'Data type :{MayankSangwan.dtype}')
print(f'Bytes per elements: {MayankSangwan.itemsize}')
print(f'Total bytes: {MayankSangwan.itemsize * MayankSangwan.size}')
print(f'Reshaped :{MayankSangwan.reshape(25,1)}')

print(MayankSangwan.reshape(25,1).T)
# Since we made a 1-D array there is not any rows or columns and just one dimensional array
# so transposing will not affect it in any way

The array formed :[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions :1
Shape: (25,)
Elements: 25
Data type :float64
Bytes per elements: 8
Total bytes: 200
Reshaped :[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]


**Q5.** Create a 2-D Array of three rows and four columns, named ucs420_<\your_name>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements.

 Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<\your_name>>. Resize the array to two rows and three columns and name it as resized_ ucs420_<\your_name>>.

In [ ]:
ucs420_MayankSangwan = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35])
ucs420_MayankSangwan = ucs420_MayankSangwan.reshape(3,4)
print(f'Original :{ucs420_MayankSangwan}')

print(f'Mean: {np.mean(ucs420_MayankSangwan)}')
print(f'Median: {np.median(ucs420_MayankSangwan)}')
print(f'Max: {np.max(ucs420_MayankSangwan)}')
print(f'Min: {np.min(ucs420_MayankSangwan)}')

x,y=np.unique(ucs420_MayankSangwan, return_counts= True)
print(f'Unique Elements: {x}')
print(f'Their count: {y}')

reshaped_ucs420_Mayank = ucs420_MayankSangwan.reshape(4,3)
print(f'Reshaped : {reshaped_ucs420_Mayank}')
resized_ucs420_MayankSangwan = ucs420_MayankSangwan.copy()
resized_ucs420_MayankSangwan.resize(2, 3)
print(f'Resized: {resized_ucs420_MayankSangwan}')

Original :[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Their count: [1 1 2 1 1 1 1 1 1 1 1]
Reshaped : [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized: [[10 20 30]
 [40 50 60]]
